# Copyright 2018 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# DO NOT MANUALLY EDIT!
# Generated by //scripts/sdk/bazel/generate.py.


load("@io_bazel_rules_dart//dart/build_rules/internal:pub.bzl", "pub_repository")

def setup_dart():
    pub_repository(
        name = "vendor_meta",
        output = ".",
        package = "meta",
        version = "1.1.6",
        pub_deps = [],
    )
    pub_repository(
        name = "vendor_logging",
        output = ".",
        package = "logging",
        version = "0.11.3+2",
        pub_deps = [],
    )
    pub_repository(
        name = "vendor_uuid",
        output = ".",
        package = "uuid",
        version = "1.0.3",
        pub_deps = [],
    )
